version: '3.8'

services:
  nest-skill-api:
    container_name: nest-skill-api
    restart: always
    image: node:20.10.0
    ports:
      - '4001:3010'
    volumes:
      - ./:/usr/src/nest-skill
    working_dir: /usr/src/nest-skill

    networks:
      - monorepo_network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  nest-batch:
    container_name: nest-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - '4002:3011'
    volumes:
      - ./:/usr/src/nest-skill
    working_dir: /usr/src/nest-skill

    networks:
      - monorepo_network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo_network:
    driver: bridge

  # FOR DEVELOPMENT
  # command: bash -c "npm install && npm run start:dev"
